apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kube-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mouadrarhib0031/kube-tasks-backend:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/kube_tasks_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: mouadcr7
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
